FROM oven/bun:1

WORKDIR /app

# Copy dependency configs
COPY package.json bun.lockb* ./

# Install dependencies
RUN bun install

# Copy source code
COPY . .

# Expose port
EXPOSE 5000

# Start app
CMD ["bun", "run", "src/index.js"]